### ISSUE TITLE
[Bug] Yarn Install for Website Folder currently leads to a webworker issue

### ISSUE THREAD

**Issue by iamalwaysuncomfortable** [AleoHQ/aleo#638]
## 🐛 Bug Report

Currently `yarn install` within the website folder does not work, which leads to a broken local development server.

## Steps to Reproduce

1. `cd website`
2. `yarn install`
3. `yarn dev`
4. Navigate to the uri reported by vite

## Expected Behavior

Yarn install should work the same way npm install does

**Comment by onetrickwolf** [comment]
After some research, seems to be an issue with how yarn builds local file modules vs where the vite dev server is expecting them to be. Can be fixed by replacing `file` with `link` (e.g. `"@aleohq/wasm": "link:../wasm/pkg-parallel"`) but this would break npm installations. Yarn doesn't recommend mixing multiple package managers anyway so I'd recommend just removing yarn, we don't really use any yarn specific feature or benefit much from it at this point.
