### ISSUE TITLE
[Feature] Expose Uint8Array<->Field conversion for signing data off-chain and verifying signatures on-chain

### ISSUE THREAD

**Issue by Scratch-net** [AleoHQ/aleo#748]
## 🚀 Feature

We need to sign arbitrary strings off-chain and verify signatures on-chain. 
But on-chain we can only verify `fields` 
`Account.sign()` does the signing string job, but all conversion happens under the hood and there's no way to extract field values needed for passing them later to leo transitions

## Motivation

A task when something needs to be signed off-chain and validated on-chain is pretty common and there's no easy way to do this right now

## Implementation
I suspect exposing [this](https://github.com/AleoHQ/snarkVM/blob/3961438b69c35715b802a24a3f3e301b5020f2a9/console/account/src/signature/sign.rs#L73C13-L73C13) line as a separate method returning a list of fields should be enough

**Comment by d0cd** [comment]
There have been a lot of questions about creating and verifying signatures, so I wanted to add some context with an example.

Here is a sample Leo program that verifies a signature on a user-defined struct.
```leo
program sigverify.aleo {

    struct Order {
        recipient: address,
        amount: u128,
    }

    transition verify(
        public sig: signature, 
        public addr: address, 
        public msg: Order, 
    ) -> bool {
        return signature::verify(sig, addr, msg);
    }
}
```

In order to generate a signature off-chain, one can use the existing snarkVM libraries in the following way.
```rust
// main.rs
use snarkvm::console::account::{private_key::*, signature::*, Address};
use snarkvm::console::network::prelude::*;
use snarkvm::console::program::{Value};
use snarkvm::prelude::Testnet3;

use std::convert::TryFrom;

fn main() {
    let rng = &mut TestRng::default();

    // Generate a random private key.
    let private_key = PrivateKey::<Testnet3>::new(rng).unwrap();

    // Create a value to be signed.
    let value = Value::from_str("{ recipient: aleo1hy0uyudcr24q8nmxr8nlk82penl8jtqyfyuyz6mr5udlt0g3vyfqt9l7ew, amount: 10u128 }").unwrap();

    // Transform the value into a message (a sequence of fields).
    let message = value.to_fields().unwrap();

    // Produce a signature.
    let signature =
        Signature::<Testnet3>::sign(&private_key, &message, rng).unwrap();

    // Verify the signature.
    let address = Address::try_from(&private_key).unwrap();
    assert!(signature.verify(&address, &message));

    // Print the results.
    print!("{signature}");
    print!(" {address}");
    print!(" \"{value}\"")
}
```

Running the above Rust code produces the following output
```
sign1yhe0g7tgyucfqrp50pvway4m9uus4fe5gd829k07xsvxrmsp65pde0jkl74l4lsjveratctvzvp6n843x7mtpsytn5wqz62yafksyqfvmyr6pqyg6sphe922j00uew8e66nkxmdspyf3ctf5y900v340qgh8yzuen5pwu40kphyxtmrx0pxl305nez5utc27x0e0e3tg2huqzzg5hxd aleo1exnzsysrz25yq2wf25e5jxy69gfzj704lcs3h2j4hp6wnuk69vfq7da29g "{
  recipient: aleo1hy0uyudcr24q8nmxr8nlk82penl8jtqyfyuyz6mr5udlt0g3vyfqt9l7ew,
  amount: 10u128
}
```
which can be passed as input to the `leo execute` command to get a successfully verified signature.

Given this example, what is required to support your application?

**Comment by Scratch-net** [comment]
a TS version of this code :)

**Comment by iamalwaysuncomfortable** [comment]
The SDK code for signing runs the signature algorithm outside of the context of a circuit. However when running a circuit via a leo function, and given the function executes properly and gives you a `false` there is no problem here.

What I imagine is happening here is that Leo types like `Field` `Scalar` `Group` etc. have a canonical byte encoding that is different from what you would get if you do:
```javascript
const bytes = textEncoder.encode('123Field')
const sign = account.sign(bytes)
```

The code above will create utf-8 bytes which will lead to a different byte encoding than the 123Field type within Leo.  And this why this function is likely failing:
```
    transition verify_field(public s: signature, public a: address, public v: field) ->bool {
        return signature::verify(s, a, v);
    }
```

Currently there's not yet a function that will first try to serialize these types into the correct byte encoding in the SDK, but I'll put a ticket in to support this (i.e. Create "a TS version of this code"). However, I will say that it will likely include the .to_fields method expressed above. It will be likely more encapsulated to simply take the string representation of the Leo types so that the input to the SDK and CLI for signing functions will match.

I will keep this issue open to track this issue.

**Comment by alipostaci2001** [comment]
thanks for info

**Comment by mwyatt896** [comment]
@d0cd @iamalwaysuncomfortable @Scratch-net 


We've added signing that returns outputs compatible for Leo program signature verification to our SDK [here](https://docs.puzzle.online/functions/requestsignature/)


You can play with it at dev.puzzle.online

<img width="1650" alt="image" src="https://github.com/AleoHQ/sdk/assets/39972641/784f7553-10e2-46b3-9d09-c3a663b902fc">


We convert the string to to Uin8Array then pass that to our modified aleo-wasm. The aleo-wasm takes the U8int and casts to fields to sign, but our modifications take that those fields and cast to a plaintext struct:
field_1: ....field,
field_2: ....field,
field_3: ....field,
field_4: ....field,
field_5: ....field,

We then convert this plaintext struct to fields and sign over that. 
The signature we return is that.

So we take input string and go:
- U8intArray
- Field
- Message Struct String (same format as Leo Program Struct that gets interpreted as Plaintext)
- Field'

Then we sign Field' and return Signature,Message Struct String

**Comment by mwyatt896** [comment]
@Scratch-net 
The reason we do this is because anything that needs to be encoded with >1 field runs into an existing Leo nuance when structs are being used in message verification.

Leo signature verification when message is a struct ends up treating the entire message as Plaintext and thus converts that Plaintext object to a field -- even if the Leo type of a value in the struct may be set as a field.

Leo signature verification works in the following way:
Takes signature.compute key and makes — 
pk_sig
pr_sig
address

takes in signature.response, signature.challenge, and pk_sig to make:
g_r:= (signature.response * G) + (signature.challenge  + pk_sig)

takes the Message Struct and does: 
Message.to_field():=
[field_1: ....field.to_field(),
field_2: ....field.to_field(),
field_3: ....field.to_field(),
field_4: ....field.to_field(),
field_5: ....field.to_field()]

and now verifies by constructing challenge' as:
H'([g_r', pk_sig, pr_sig, address, Message.to_field()]

The signature verification would fail if we didn't do the additional step to cast Field to Message as Struct to Field' and return Message as Struct to the signer to input to Leo program.

**Comment by Scratch-net** [comment]
Whatever :)

**Comment by mwyatt896** [comment]
@d0cd @Scratch-net @iamalwaysuncomfortable 

You can view, verify and test signature verification in Leo program this way via our Where's Alex programs here:

https://github.com/puzzlehq/serengeti/blob/main/README.md

**Comment by Scratch-net** [comment]
It's not relevant for us any more, so have a nice day.
